window.LOTUS_PLACES = [
  {
    id: "wailea-path",
    name: "Wailea Beach Path",
    type: "run",
    lat: 20.6825,
    lng: -156.4428,
    energy: ["medium", "high"],
    timeOfDay: ["morning", "afternoon"],
    focus: ["movement", "mix"],
    distance: "1.6 mi one way · ~3.2 mi round",
    duration: "30–50 min",
    description: "The paved oceanfront path that runs past the resorts. Scenic, gentle, and quietly judgmental of anyone who skips it.",
    tips: "Start near Ulua or Polo Beach. Early morning is best before the heat and the influencer crowd.",
    mapQuery: "Wailea Beach Path Maui"
  },
  {
    id: "kihei-coastal",
    name: "Kihei Coastal Run",
    type: "run",
    lat: 20.7550,
    lng: -156.4570,
    energy: ["medium", "high"],
    timeOfDay: ["morning"],
    focus: ["movement"],
    distance: "2–5 mi flexible",
    duration: "25–55 min",
    description: "Beach-adjacent paths and roads along South Kihei. Less polished than Wailea, more local rhythm.",
    tips: "Kamaole beaches area works well. Combine with a swim if the energy is still there.",
    mapQuery: "Kamaole Beach Park Kihei"
  },
  {
    id: "hoapili",
    name: "Hoapili Trail (La Perouse)",
    type: "hike",
    lat: 20.5910,
    lng: -156.4150,
    energy: ["high"],
    timeOfDay: ["morning", "midday"],
    focus: ["movement", "explore"],
    distance: "Up to 5+ mi out-and-back",
    duration: "2–4 hrs",
    description: "Lava fields, ocean views, and the feeling that the island was here long before the resorts. Rough underfoot.",
    tips: "Bring water and good shoes. Best early. This is the anti-resort option.",
    mapQuery: "Hoapili Trail La Perouse Bay Maui"
  },
  {
    id: "twin-falls",
    name: "Twin Falls",
    type: "hike",
    lat: 20.9120,
    lng: -156.2450,
    energy: ["medium"],
    timeOfDay: ["morning", "midday"],
    focus: ["explore", "mix"],
    distance: "~1.5–2 mi round",
    duration: "1–1.5 hrs",
    description: "Easy waterfall stop on the way toward Hana. Touristy in the best and worst ways.",
    tips: "Go early. Combine with a longer Road to Hana day if the mood strikes.",
    mapQuery: "Twin Falls Maui"
  },
  {
    id: "south-maui-fish",
    name: "South Maui Fish Company",
    type: "eat",
    lat: 20.7355,
    lng: -156.4480,
    energy: ["low", "medium", "high"],
    timeOfDay: ["midday", "afternoon"],
    focus: ["food", "mix"],
    distance: null,
    duration: "30–60 min",
    description: "Consistently mentioned as some of the best poke on the island. No pretense, just excellent fish.",
    tips: "Limited hours. Check before you go. Worth the short drive from Wailea.",
    mapQuery: "South Maui Fish Company Kihei"
  },
  {
    id: "tamuras-poke",
    name: "Tamura's (Kihei)",
    type: "eat",
    lat: 20.7600,
    lng: -156.4550,
    energy: ["low", "medium"],
    timeOfDay: ["midday", "afternoon"],
    focus: ["food"],
    distance: null,
    duration: "20–40 min",
    description: "Liquor store that also happens to have very good poke. The kind of place the show would quietly approve of.",
    tips: "Casual counter. Grab and go or eat nearby.",
    mapQuery: "Tamura's Fine Wine Kihei"
  },
  {
    id: "foodland-poke",
    name: "Foodland Farms Poke",
    type: "eat",
    lat: 20.7500,
    lng: -156.4555,
    energy: ["low", "medium"],
    timeOfDay: ["midday", "afternoon"],
    focus: ["food"],
    distance: null,
    duration: "15–30 min",
    description: "Reliable, high-quality poke counter inside a grocery store. Efficient. Unpretentious.",
    tips: "Good when you want excellent fish without a full restaurant commitment.",
    mapQuery: "Foodland Farms Kihei"
  },
  {
    id: "makena-beach",
    name: "Makena / Big Beach",
    type: "beach",
    lat: 20.6290,
    lng: -156.4460,
    energy: ["low", "medium"],
    timeOfDay: ["morning", "midday", "afternoon"],
    focus: ["chill", "mix", "movement"],
    distance: null,
    duration: "Flexible",
    description: "Wide, dramatic beach south of Wailea. The water does most of the talking.",
    tips: "Morning light is excellent. Can be windy. Bring layers of intention.",
    mapQuery: "Makena Beach Maui"
  },
  {
    id: "ulua-beach",
    name: "Ulua Beach",
    type: "beach",
    lat: 20.6900,
    lng: -156.4435,
    energy: ["low", "medium"],
    timeOfDay: ["morning", "afternoon"],
    focus: ["chill", "mix"],
    distance: null,
    duration: "Flexible",
    description: "Convenient Wailea beach with good snorkeling on calm days and direct access to the path.",
    tips: "Easy parking relative to other Wailea spots. Good post-run cooldown.",
    mapQuery: "Ulua Beach Wailea"
  },
  {
    id: "iao-valley",
    name: "Iao Valley State Monument",
    type: "hike",
    lat: 20.8805,
    lng: -156.5450,
    energy: ["medium"],
    timeOfDay: ["morning", "midday"],
    focus: ["explore"],
    distance: "Short paved + optional trails",
    duration: "1–2 hrs",
    description: "Lush, dramatic, and close to Kahului. The Needle is the main character.",
    tips: "Reservations sometimes required. Go early for softer light and fewer people.",
    mapQuery: "Iao Valley State Monument"
  },
  {
    id: "wailea-breakfast",
    name: "Wailea-style breakfast",
    type: "eat",
    lat: 20.6900,
    lng: -156.4430,
    energy: ["low"],
    timeOfDay: ["morning"],
    focus: ["food", "chill"],
    distance: null,
    duration: "45–90 min",
    description: "The classic slow start. Ocean view, carefully arranged fruit, the quiet performance of leisure.",
    tips: "Lean into it once if you're nearby. Then return to poke and clarity.",
    mapQuery: "Wailea Maui breakfast"
  },
  {
    id: "kapalua-coastal",
    name: "Kapalua Coastal Trail",
    type: "run",
    lat: 20.9980,
    lng: -156.6670,
    energy: ["medium"],
    timeOfDay: ["morning", "afternoon"],
    focus: ["movement", "explore"],
    distance: "~1.5–3 mi",
    duration: "30–60 min",
    description: "West Maui option. Dramatic coastline, more wind, different energy from the south side.",
    tips: "Worth the drive when you want a change of scenery.",
    mapQuery: "Kapalua Coastal Trail Maui"
  }
];
